/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as AlignRouteImport } from './routes/align'
import { Route as IndexRouteImport } from './routes/index'

const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignRoute = AlignRouteImport.update({
  id: '/align',
  path: '/align',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/roi': typeof RoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/align': typeof AlignRoute
  '/roi': typeof RoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/align' | '/roi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/align' | '/roi'
  id: '__root__' | '/' | '/align' | '/roi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignRoute: typeof AlignRoute
  RoiRoute: typeof RoiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/align': {
      id: '/align'
      path: '/align'
      fullPath: '/align'
      preLoaderRoute: typeof AlignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignRoute: AlignRoute,
  RoiRoute: RoiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
